trigger:
- main # Triggers when code is pushed to the main branch
pool:
vmImage: ubuntu-latest
steps:
# Step 1: Checkout the repository
- task: Checkout@1
# Step 2: Set up Python
- task: UsePythonVersion@0
inputs:
versionSpec: '3.10'
addToPath: true
# Step 3: Install dependencies
- script: |
python -m pip install --upgrade pip
pip install -r data_pipeline/requirements.txt
displayName: 'Install dependencies'
# Step 4: Run the data fetcher
- script: |
cd data_pipeline
python fetch_data.py
displayName: 'Fetch raw data'
# Step 5: Process the data
- script: |
cd data_pipeline
python process_data.py
displayName: 'Process data'
# Step 6: Publish the processed file as an artifact
- task: PublishBuildArtifacts@1
inputs:
PathtoPublish: 'data_pipeline/processed_data.json'

ArtifactName: 'ProcessedData'
publishLocation: 'Container'